name: CI Pipeline for Push and Pull Request

on:
  push:
    branches:
      - main

env:
  APP_SCHEME: "PokedexApp"
  
jobs:
  build-and-test:
    name: Build and Test
    runs-on: macos-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        
      - name: Cache Tuist dependencies
        uses: actions/cache@v3
        id: tuist-cache
        with:
          path: |
            Tuist/Dependencies/SwiftPackageManager
            Tuist/Dependencies/graph.json
            ~/.tuist/Cache
          key: ${{ runner.os }}-tuist-${{ hashFiles('Workspace.swift', 'Tuist/Dependencies/Lockfiles/*') }}
          restore-keys: |
            ${{ runner.os }}-tuist-
            
      - name: Install Tuist if not present
        run: |
          if ! command -v tuist > /dev/null 2>&1; then
            curl -Ls https://install.tuist.io | bash
          fi
      
      - name: Fetch Tuist dependencies
        run: tuist fetch
          
      - name: Build PokedexApp
        run: tuist build "${{ env.APP_SCHEME }}"
        env:
          TUIST_IS_CI: 1
          
      - name: Test all modules
        run: tuist test
        env:
          TUIST_IS_CI: 1
